#!/usr/bin/env node
import { mkdir, readFile, writeFile } from "node:fs/promises";

const checkOnly = process.argv.includes("--check");
const baseUrl = process.env.GZW_API_URL ?? "https://gzw-data.dev/api/v1";
const metadataUrl = `${baseUrl.replace(/\/+$/, "")}/metadata?full=true`;
const response = await fetch(metadataUrl);
if (!response.ok) throw new Error(`Metadata request failed with HTTP ${response.status}`);
const payload = await response.json();
const metadata = payload?.data ?? payload;
if (!Array.isArray(metadata?.datasets)) throw new Error("Metadata response did not contain datasets");

const datasets = metadata.datasets
  .filter((dataset) => typeof dataset?.name === "string" && /^[a-z0-9_]+$/.test(dataset.name))
  .sort((left, right) => left.name.localeCompare(right.name));
if (!datasets.length) throw new Error("Metadata did not contain usable datasets");

const names = datasets.map((dataset) => `  | "${dataset.name}"`).join("\n");
const metadataEntries = datasets.map((dataset) => {
  const fields = Object.keys(dataset.fields ?? {}).sort();
  const fieldTypes = fields.map((field) => `    ${JSON.stringify(field)}: ${JSON.stringify(dataset.fields[field].types ?? [])}`).join(",\n");
  return `  ${JSON.stringify(dataset.name)}: { count: ${Number(dataset.itemCount) || 0}, fields: {\n${fieldTypes}\n  } }`;
}).join(",\n");

const output = `// Generated by scripts/generate-types.mjs. Do not edit manually.\n// Source: ${metadataUrl}\n\nexport type GeneratedDatasetName =\n${names};\n\nexport type GeneratedDatasetInfo = {\n  count: number;\n  fields: Record<string, string[]>;\n};\n\nexport const generatedDatasetInfo: Record<GeneratedDatasetName, GeneratedDatasetInfo> = {\n${metadataEntries}\n};\n`;

await mkdir("src/generated", { recursive: true });
const target = "src/generated/datasets.ts";
let current = "";
try { current = await readFile(target, "utf8"); } catch {}
if (checkOnly) {
  if (current !== output) {
    console.error(`${target} is stale. Run npm run generate-types.`);
    process.exit(1);
  }
  console.log(`${target} is up to date.`);
} else if (current !== output) {
  await writeFile(target, output);
}
console.log(`${checkOnly ? "Checked" : "Generated"} ${target} for ${datasets.length} datasets.`);
